# Theme
ZSH_THEME="neat"

# Enable command auto-correction
ENABLE_CORRECTION="true"

# Plugins
plugins=(git osx nvm zsh-autosuggestions zsh-syntax-highlighting)

# User configuration

# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# Language environment
export LANG=en_US.UTF-8

# Preferred editor
export EDITOR='vim'

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias update-zshrc="curl -o $ZSH/update.sh -fsSL https://raw.githubusercontent.com/stevenmirabito/steven-zshrc/master/setup.sh && zsh $ZSH/update.sh && rm -f $ZSH/update.sh"

